# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings



paginate: 10 # pagination based on number of posts

paginate_path: "page:num"

exclude: ["README.md"] # files to exclude

highlighter: rouge

markdown: kramdown

disqus: dbyll

google_analytics: dbyll
 
title: dbyll



defaults:

  -

    scope:
 
      path: "" # empty string for all files

    values:

      title: yhevrmt



description: Stylish Jekyll Theme

author:

  name: 百岁髑髅

  email: 3291666270@qq.com

  github: yhevrmt

  twitter: dbtek

  pinterest: asd123

  linkedin: asd123

  bio: 万物皆出于机 ，皆入于机。

  email_md5: 726351295ec82e145928582f595aa3aa



rss_path: feed.xml

categories_path: categories.html

tags_path: tags.html



# set it as url of an image

# sidebar_background_image: /congenial-octo-adventure/image/background.jpg



BASE_PATH: /congenial-octo-adventure



gems:

  - jekyll-paginate
